" Lade Plugins
if filereadable(expand('~/.vim/plugins.vim'))
	source ~/.vim/plugins.vim
endif

" Lese systemspezifische Konfiguration
if filereadable(expand('~/.vim/local.vim'))
	source ~/.vim/local.vim
endif

" syntax highlighting
filetype plugin indent on
syntax on

" Zeilennummern
set number

" Vergrößere das Fenster, weil sonst keine 80 Zeichen mehr passen
set columns=84

" Hebe aktuelle Zeile hervor
set cursorline

" Bildschirm nicht refreshen wenn makros ausgeführt werden
set lazyredraw

" Persistent undo
" Das has(...) ist da, weil auf den Rechnern im CIP Pool kein ausreichend
" aktuelles vim drauf ist
if has('persistent_undo')
	set undodir=$HOME/.vim/undo
	set undofile
endif

" Erlaubt es den buffer zu wechseln obwohl es ungespeicherte Änderungen gibt
set hidden

" Farbschema
set bg=dark
colorscheme solarized

" Hebe Whitespace Fehler hervor
highlight WhitespaceError ctermbg=red guibg=red
" Mach Whitespace am Ende einer Zeile rot
let wm1=matchadd('WhitespaceError', '\s\+\%#\@<!$')
" Mach Leerzeichen vor Tabs rot
let wm2=matchadd('WhitespaceError', ' \+\ze\t')

if has("gui_running")
	" Schalte Menüleiste aus
	set guioptions-=m
else
	" Mausunterstützung im Terminal
	set mouse=a
endif


" ===========================================================================
" Keymappings

" Setze <Leader>
let mapleader=" "

" Mappe jk als Escape
inoremap jk <Esc>

" Kopiere in die Zwischenablage
nnoremap <Leader>y "+y
nnoremap <Leader>Y "+Y
vnoremap <Leader>y "+y
vnoremap <Leader>Y "+Y

" Lösche in die Zwischenablage
nnoremap <Leader>d "+d
nnoremap <Leader>D "+D
vnoremap <Leader>d "+d
vnoremap <Leader>D "+D

" Einfügen von der Zwischenablage
nnoremap <Leader>p "+p
nnoremap <Leader>P "+P
vnoremap <Leader>p "+p
vnoremap <Leader>P "+P

" Fenster befehle

" bewegen
nnoremap <silent> <Leader>h :wincmd h<CR>
nnoremap <silent> <Leader>j :wincmd j<CR>
nnoremap <silent> <Leader>k :wincmd k<CR>
nnoremap <silent> <Leader>l :wincmd l<CR>

" größe ändern
nnoremap <silent> <Leader>_ :wincmd _<CR>
nnoremap <silent> <Leader>= :wincmd =<CR>
nnoremap <silent> <Leader>\| :wincmd \|<CR>

" CtrlP
nnoremap <Leader>t <c-]>
nnoremap <Leader>z <c-t>
nnoremap <Leader>f :CtrlP<CR>
nnoremap <Leader>r :CtrlPTag<CR>

" Undotree
nnoremap <silent> <Leader>u :UndotreeToggle<CR>:UndotreeFocus<CR>

" ===========================================================================
" Dateispezifische Einstellungen

" Spaces statt tabs für rust
autocmd FileType rust setlocal shiftwidth=4 tabstop=4 softtabstop=4 expandtab

" Spaces statt tabs für haskell
autocmd FileType haskell setlocal shiftwidth=4 tabstop=4 softtabstop=4 expandtab

" Keine Zeilennummern für vims Hilfedateien
autocmd FileType help setlocal nonumber
